In [1]:
import math

In [2]:
data = 21.6
print('The floor of 21.6 is:', math.floor(data))

The floor of 21.6 is: 21


In [3]:
print('The value of PI:',math.pi)

The value of PI: 3.141592653589793


In [4]:
print(math.pow(2, 3))

8.0


In [5]:
data = 24.3
print(math.ceil(data))

25


In [6]:
angleInDegree = 90
angleInRadian = math.radians(angleInDegree)

print('The given angle is :', angleInRadian)
print('sin(x) is :', math.sin(angleInRadian))
print('cos(x) is :', math.cos(angleInRadian))
print('tan(x) is :', math.tan(angleInRadian))

The given angle is : 1.5707963267948966
sin(x) is : 1.0
cos(x) is : 6.123233995736766e-17
tan(x) is : 1.633123935319537e+16


In [7]:
number = 1e-4
print('The given number (x) is :', number)
print('e^x (using exp() function) is :', math.exp(number)-1)
print('log(fabs(x), base) is :', math.log(math.fabs(number), 10))

The given number (x) is : 0.0001
e^x (using exp() function) is : 0.0001000050001667141
log(fabs(x), base) is : -3.999999999999999


In [8]:
import statistics

li = [1, 2, 3, 3, 2, 2, 2, 1]

print ("The average of list values is : ",end="")
print (statistics.mean(li))

print ("The maximum occurring element is : ",end="")
print (statistics.mode(li))

print ("The median of list element is : ",end="")
print (statistics.median(li))

print ("The lower median of list element is : ",end="")
print (statistics.median_low(li))

print ("The higher median of list element is : ",end="")
print (statistics.median_high(li))

print ("The 50th percentile of data is : ",end="")
print (statistics.median_grouped(li))


The average of list values is : 2
The maximum occurring element is : 2
The median of list element is : 2.0
The lower median of list element is : 2
The higher median of list element is : 2
The 50th percentile of data is : 2.0


In [9]:
import numpy as np
lst = [2,3, 7.9, 3.3, 6.9, 0.11, 10.3, 12.9]
v = np.array(lst)
v = v + 2
print(v)

[ 4.    5.    9.9   5.3   8.9   2.11 12.3  14.9 ]


In [10]:
print(v * 2.2)

[ 8.8   11.    21.78  11.66  19.58   4.642 27.06  32.78 ]


In [12]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))

print("Adding to arrays: ")
print(A + B)

print("\nMultiplying two arrays: ")
print(A * (B + 1))

Adding to arrays: 
[[12. 13. 14.]
 [22. 23. 24.]
 [32. 33. 34.]]

Multiplying two arrays: 
[[22. 24. 26.]
 [42. 44. 46.]
 [62. 64. 66.]]


In [1]:
from scipy import special
a = special.exp10(3)
print(a)
 
b = special.exp2(3)
print(b)
 
c = special.sindg(90)
print(c)
 
d = special.cosdg(45)
print(d)

1000.0
8.0
1.0
0.7071067811865475
